### ISSUE TITLE
Subprocess or spark-submit error

### ISSUE THREAD

**Issue by aflaxman** [p-b-j/census-das-container#2]
I got past the block from issue #1 by downloading an academic license, and now I am running into an issue about `subprocess` starting `spark-submit`. Maybe I need to install something else?

```
E           subprocess.CalledProcessError: Command '['spark-submit', '/ihme/homes/abie/projects/2021/census-das-container/census2020-das-e2e/tests/gurobi_2_test.py', '--sparkworkers']' returned non-zero exit status 1.

/usr/local/anaconda3/lib/python3.6/subprocess.py:291: CalledProcessError
------------------------------------------------------------- Captured stderr call --------------------------------------------------------------
Exception in thread "main" java.io.IOException: Failed to create a temp directory (under /tmp) after 10 attempts!
       at org.apache.spark.util.Utils$.createDirectory(Utils.scala:311)
       at org.apache.spark.util.Utils$.createTempDir(Utils.scala:332)
       at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:324)
       at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:774)
       at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
       at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
       at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
       at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
       at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
       at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
=========================================================== 1 failed in 2.40 seconds ============================================================
```

**Comment by p-b-j** [comment]
Ah it looks like it might be a permissions issue with `/tmp`. I think it might be resolvable by running the following (from the top-level of the repository):
```
# Create folder to use as temporary storage
$ mkdir singularity_tmp
# bind the container's temporary directory to the new directory
$ singularity run --home $HOME --bind singularity_tmp:/tmp census_das.img
```

**Comment by aflaxman** [comment]
That gets me further, but I've got a new permission error now:
```
py.test tests/gurobi_2_test.py
============================================================== test session starts ==============================================================
platform linux -- Python 3.6.5, pytest-3.5.1, py-1.5.3, pluggy-0.6.0
rootdir: /ihme/homes/abie/projects/2021/census-das-container/census2020-das-e2e, inifile:
plugins: remotedata-0.2.1, openfiles-0.3.0, doctestplus-0.1.3, arraydiff-0.2
collected 1 item

tests/gurobi_2_test.py .                                                                                                                  [100%]

=========================================================== 1 passed in 6.80 seconds ============================================================
mkdir: cannot create directory '/home/abie': Read-only file system
```

**Comment by p-b-j** [comment]
Ah bummer, this one looks like a poorly defined home directory in `census2020-das-e2e/run_1940_standalone.sh`, I just pushed a fix that should get you passed this hurdle (not going to promise you won't discover another issue...).

**Comment by aflaxman** [comment]
I think it is working now!

**Comment by p-b-j** [comment]
Added instructions for the first error to the README, and given that the second error was resolved (and we've moved to discussing further issues in #3), I'll close this issue.
